### ISSUE TITLE
Invalid Link

### ISSUE THREAD

**Issue by ghost** [Melody1024/anti996_law#2]
https://share.weiyun.com/5RYZib6 密码：p57aec
失效的最后一秒，下载成功，真是笑死人了

😓我看看什么原因

**Comment by Melody1024** [comment]
> https://share.weiyun.com/5RYZib6 密码：p57aec
> 失效的最后一秒，下载成功，真是笑死人了
> 
> 😓我看看什么原因

依据恢复正常了

**Comment by ghost** [comment]
> 
> 
> > https://share.weiyun.com/5RYZib6 密码：p57aec
> > 失效的最后一秒，下载成功，真是笑死人了
> > 😓我看看什么原因
> 
> 依据恢复正常了

嗯，我已经下载了，是微云提示违规资源，现在正常了

**Comment by Melody1024** [comment]
> > > https://share.weiyun.com/5RYZib6 密码：p57aec
> > > 失效的最后一秒，下载成功，真是笑死人了
> > > 😓我看看什么原因
> > 
> > 
> > 依据恢复正常了
> 
> 嗯，我已经下载了，是微云提示违规资源，现在正常了

当时我在重传文件到文件夹，故意是被锁住了

**Comment by iPhotoner** [comment]
close issue

**Comment by gh0sthx** [comment]
链接已删除，请联系分享者重新分享。
